import { createSlice } from "@reduxjs/toolkit"; // import createSlice function from Redux Toolkit to define a slice of the Redux store with state, reducers, and actions

const initialState = { // define the initial state object for the auth slice
    user: null, // set 'user' to null initially indicating no user is logged in
    isAuthenticated: false, // set 'isAuthenticated' to false initially indicating the user is not authenticated
};

const authSlice = createSlice({ // define a Redux slice named authSlice to handle authentication state
    name: "authSlice", // set the slice name to "authSlice", which prefixes generated action types
    initialState, // assign the previously defined initialState as the default state for this slice
    reducers: { // define reducer functions to update state based on dispatched actions
        userLoggedIn: (state, action) => { // define a reducer 'userLoggedIn' that updates state when a user logs in
            state.user = action.payload.user; // update the 'user' field in state with the 'user' from action payload
            state.isAuthenticated = true; // set 'isAuthenticated' to true to indicate user is logged in
        },
        userLoggedOut: (state) => { // define a reducer 'userLoggedOut' that updates state when a user logs out
            state.user = null; // reset 'user' to null indicating no user is logged in
            state.isAuthenticated = false; // set 'isAuthenticated' to false indicating the user is logged out
        }
    },
});

export const { userLoggedIn, userLoggedOut } = authSlice.actions; // export the generated action creators 'userLoggedIn' and 'userLoggedOut' for dispatching actions
export default authSlice.reducer; // export the reducer function generated by createSlice as the default export so it can be integrated into the Redux store
