import { createSlice } from "@reduxjs/toolkit" // import createSlice function from Redux Toolkit to easily create a slice of the Redux store with actions and reducers

const authSlice = createSlice({ // define a constant authSlice by calling createSlice to create authentication-related state logic
    name: "auth", // specify the name of this slice as 'auth' to identify it within the Redux store

    initialState: { // define the initial state object for authentication-related data
        user: null, // initialize user as null to represent no logged-in user initially
        suggestedUsers: [], // initialize suggestedUsers as an empty array to hold suggested user data later
        userProfile: null, // initialize userProfile as null to store the current user’s profile when available
        selectedUser: null, // initialize selectedUser as null to store data of a selected user from suggestions or searches
    },

    reducers: { // define an object of reducer functions that update specific parts of the state
        setAuthUser: (state, action) => { // define a reducer setAuthUser that takes state and action to update user information
            state.user = action.payload; // assign the payload from the dispatched action to state.user to update the current authenticated user
        },
        setSuggestedUsers: (state, action) => { // define a reducer setSuggestedUsers that takes state and action to update suggested users
            state.suggestedUsers = action.payload; // assign the payload array to state.suggestedUsers to update the list of suggested users
        },
        setUserProfile: (state, action) => { // define a reducer setUserProfile that takes state and action to update the user profile data
            state.userProfile = action.payload; // assign the payload object to state.userProfile to update the displayed profile data
        },
        setSelectedUser: (state, action) => { // define a reducer setSelectedUser that takes state and action to update the selected user information
            state.selectedUser = action.payload; // assign the payload data to state.selectedUser to change which user is currently selected
        }
    }
});

export const { // export individual action creators generated automatically by createSlice for use in dispatch calls
    setAuthUser, // export the action creator for updating authenticated user data
    setSuggestedUsers, // export the action creator for updating suggested users
    setUserProfile, // export the action creator for updating user profile data
    setSelectedUser, // export the action creator for updating selected user
} = authSlice.actions;

export default authSlice.reducer; // export the reducer function generated by createSlice to be added to the Redux store
