import { createSlice } from "@reduxjs/toolkit"; // import createSlice function from Redux Toolkit to easily create a slice with state, reducers, and actions

const postSlice = createSlice({ // define a constant postSlice by calling createSlice to manage post-related state and logic
    name: 'post', // assign the slice name 'post' to uniquely identify it in the Redux store

    initialState: { // define the initial state object for posts
        posts: [], // initialize posts as an empty array to store multiple post objects
        selectedPost: null, // initialize selectedPost as null to represent no post currently selected
    },

    reducers: { // define an object of reducer functions that handle updates to specific parts of the state
        setPosts: (state, action) => { // define a reducer setPosts that takes state and action to update the posts array
            state.posts = action.payload; // assign the payload array from the dispatched action to state.posts to update all posts
        },
        setSelectedPost: (state, action) => { // define a reducer setSelectedPost that takes state and action to update the selected post
            state.selectedPost = action.payload; // assign the payload object from the dispatched action to state.selectedPost to change which post is selected
        }
    }
});

export const { setPosts, setSelectedPost } = postSlice.actions; // export the auto-generated action creators for setting posts and selected post

export default postSlice.reducer; // export the reducer function generated by createSlice to integrate into the Redux store
