import { createSlice } from "@reduxjs/toolkit"; // import createSlice function from Redux Toolkit to create a slice for managing socket.io connection state

const socketSlice = createSlice({ // define a constant socketSlice by calling createSlice to handle socket-related state management
    name: "socketio", // assign the slice name 'socketio' to identify it within the Redux store

    initialState: { // define the initial state object for socket management
        socket: null // initialize socket as null to represent no active socket connection initially
    },

    reducers: { // define an object of reducer functions to modify parts of the socket state
        setSocket: (state, action) => { // define a reducer setSocket that takes state and action to update the socket connection object
            state.socket = action.payload; // assign the payload from the action to state.socket to store or update the socket instance
        }
    }
});

export const { setSocket } = socketSlice.actions; // export the auto-generated action creator for setting the socket instance

export default socketSlice.reducer; // export the reducer generated by createSlice to integrate into the Redux store
